remote_theme: just-the-docs/just-the-docs@v0.10.0
title: FalkorDB Docs
description: The FalkorDB documentation
url: "https://docs.falkordb.com"
logo: "/images/falkor-logo.png"
logo_link: "https://www.falkordb.com"
favicon_ico: "/images/favicon.ico"
gtm_tracking: GTM-MBWB627H

search_enabled: true
color_scheme: dark

aux_links:
  "Docs Repository":
    - "https://github.com/falkordb/docs"
  "FalkorDB Repository":
    - "https://github.com/falkordb/falkordb"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable the side/mobile menu globally
nav_enabled: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/core/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/FalkorDB/docs/"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
